// ==========================================================================
//  THU VIEN TEN AFFIX CUA DIABLO.TRADE
//
//  Lay tu chinh trang wiki cong khai cua ho:  https://diablo.trade/wiki/affixes
//  (11 trang, 60 muc moi trang). KHONG phai go tay, khong phai cao tu nguon
//  thu ba - day la ten CHUAN, dung thu ma form cua ho dung.
//
//  Dung de: biet mot ten OCR doc ra co THAT SU ton tai khong, de bao cho dung
//  ("affix nay co that nhung mon do nay khong co" khac han "OCR doc bay").
//  Ten de dien vao form van lay truc tiep tu form/dropdown luc chay.
//
//  Lay ngay 2026-09-22  -  638 ten.
// ==========================================================================
var D4L_AFFIX = [
  "+1 Charm Slot",
  "100% Main Hand Weapon Damage",
  "Abyss Skills",
  "Adept Action: Damage Reduction while moving",
  "Adept Action: While standing still, you deal increased damage",
  "Advance",
  "Aegis",
  "Agility Skills",
  "All Damage Multiplier",
  "All Skills",
  "All Stats",
  "Ancient Skills",
  "Applied Alchemy: Damage to Crowd Controlled Enemies",
  "Applied Alchemy: Physical Damage",
  "Applied Alchemy: Trap Skill Damage",
  "Applied Alchemy: Trap Skills",
  "Applied Alchemy: Vulnerable Damage",
  "Applied Alchemy: to Spawn Stun Grenades after Casting Non-Trap skills.",
  "Arc Lash",
  "Armor",
  "Armored Hide",
  "Arms of Arreat: Barrier Generation",
  "Arms of Arreat: Basic Skill Damage",
  "Arms of Arreat: Cooldown Reduction to Weapon Mastery Skills",
  "Arms of Arreat: Damage when swapping weapons",
  "Arms of Arreat: Weapon Mastery Skill Damage",
  "Arms of Arreat: maximum Resolve",
  "Arrow Storm",
  "Art of the Bone Weaver: Armor",
  "Art of the Bone Weaver: Bone Skill Cooldown Reduction",
  "Art of the Bone Weaver: Bone Skill Damage",
  "Art of the Bone Weaver: Core Skill Damage",
  "Art of the Bone Weaver: Maximum Essence",
  "Art of the Bone Weaver: Movement Speed while Quintessence is active",
  "Attack Speed",
  "Attack Speed for Seconds After Dodging an Attack",
  "Attacks Reduce Evade's Cooldown by Seconds",
  "Aura Skills",
  "Balazan's Bite: Centipede Damage",
  "Balazan's Bite: Damage Over Time",
  "Balazan's Bite: Damage to Weakened enemies",
  "Balazan's Bite: Enemies Poisoned for more than their remaining Life are instantly killed seconds faster",
  "Balazan's Bite: Healing Received",
  "Balazan's Bite: Poison Damage",
  "Balazan's Bite: to Scourge",
  "Ball Lightning",
  "Barrage",
  "Barrier Generation",
  "Bash",
  "Basic Damage",
  "Basic Skills",
  "Berserk Duration",
  "Berserker's Crucible: Attack Speed while Berserking",
  "Berserker's Crucible: Berserking duration",
  "Berserker's Crucible: Damage Reduction while Berserking",
  "Berserker's Crucible: Damage while Berserking",
  "Berserker's Crucible: Lucky Hit: Chance to Become Berserking",
  "Berserker's Crucible: Movement Speed while Berserking",
  "Berserker's Crucible: to Wrath of the Berserker",
  "Blade Shift",
  "Blazing Scream",
  "Blessed Hammer",
  "Blessed Shield",
  "Blight",
  "Bliss of the Multitude: Centipede Damage",
  "Bliss of the Multitude: Eagle Skill Damage",
  "Bliss of the Multitude: Gorilla Skill Damage",
  "Bliss of the Multitude: Incarnate Skill Damage",
  "Bliss of the Multitude: Jaguar Skill Damage",
  "Bliss of the Multitude: Ultimate Skill Damage",
  "Blizzard",
  "Block Chance",
  "Blocked Damage Reduction",
  "Blood Howl",
  "Blood Lance",
  "Blood Mist",
  "Blood Skills",
  "Blood Surge",
  "Bloodletter's Flow: Bleeding Damage",
  "Bloodletter's Flow: Bloodletter's Flow Chance to Rupture enemies",
  "Bloodletter's Flow: Damage Reduction from Bleeding enemies",
  "Bloodletter's Flow: Healing Received",
  "Bloodletter's Flow: Maximum Life",
  "Bloodletter's Flow: Rupture Damage",
  "Bloodletter's Flow: Vulnerable Damage",
  "Bombardment",
  "Bone Breaker: Resource generation",
  "Bone Breaker: maximum Overpower",
  "Bone Prison",
  "Bone Skills",
  "Bone Spear",
  "Bone Spirit",
  "Bone Splinters",
  "Bonus Kill Experience",
  "Boulder",
  "Brandish",
  "Brawling Skills",
  "Breath of the Frozen Sea: Barrier Generation",
  "Breath of the Frozen Sea: Chill Application",
  "Breath of the Frozen Sea: Cold Damage",
  "Breath of the Frozen Sea: Cold Skill Damage",
  "Breath of the Frozen Sea: Damage to Crowd Controlled Enemies",
  "Breath of the Frozen Sea: Frost Cooldown Reduction",
  "Bul-Kathos' Pride: Ancient Skill Cooldown Reduction",
  "Bul-Kathos' Pride: Ancient Skill Cost Reduction",
  "Bul-Kathos' Pride: Ancient Skill Damage",
  "Bul-Kathos' Pride: Damage while Call of the Ancients is active",
  "Bul-Kathos' Pride: to Ancient Skills",
  "Bul-Kathos' Pride: to Call of the Ancients",
  "Cain's Wild Lighting: Critical Strike Chance",
  "Cain's Wild Lighting: Lightning Damage",
  "Cain's Wild Lighting: Mana per Second",
  "Cain's Wild Lighting: Movement Speed",
  "Cain's Wild Lighting: Shock Cooldown Reduction",
  "Cain's Wild Lighting: Shock Skill Damage",
  "Caltrops",
  "Can equip more Unique Charm",
  "Can equip up to 3 Unique Charms",
  "Cannot have more than 5 Sockets, but can equip 2 Unique Charms",
  "Cathan's Dauntless Faith: Attack Speed",
  "Cathan's Dauntless Faith: Critical Strike Chance",
  "Cathan's Dauntless Faith: Damage to Weakened Enemies",
  "Cathan's Dauntless Faith: Physical Damage",
  "Cathan's Dauntless Faith: Zealot Skill Cooldown Reduction",
  "Cathan's Dauntless Faith: Zealot Skill Damage",
  "Cathan's Iron Conviction: Aura Potency",
  "Cathan's Iron Conviction: Aura Skills",
  "Cathan's Iron Conviction: Faith Regeneration per Second",
  "Cathan's Iron Conviction: Maximum Faith",
  "Cathan's Iron Conviction: to Defiance Aura",
  "Cathan's Iron Conviction: to Fanaticism Aura",
  "Cathan's Iron Conviction: to Holy Light Aura",
  "Cathan's Righteous Will: Crowd Control Duration",
  "Cathan's Righteous Will: Damage to Crowd Controlled Enemies",
  "Cathan's Righteous Will: Juggernaut Skill Cooldown Reduction",
  "Cathan's Righteous Will: Juggernaut Skill Damage",
  "Cathan's Righteous Will: Maximum Resolve Stacks",
  "Cathan's Righteous Will: Thorns",
  "Centipede Skills",
  "Chain Lightning",
  "Chains of Horazon: Attack Speed",
  "Chains of Horazon: Dominance Generation",
  "Chains of Horazon: Maximum Wrath",
  "Chains of Horazon: Soul Shard Skill Cost Reduction",
  "Chains of Horazon: Soul Shard Skill Damage",
  "Chains of Horazon: Wrath Generation",
  "Challenging Shout",
  "Charge",
  "Charged Bolts",
  "Clash",
  "Claw",
  "Cold Damage Multiplier",
  "Cold Imbuement",
  "Cold Resistance",
  "Combat Skills",
  "Command Fallen",
  "Companion Skills",
  "Concealment",
  "Concussive Stomp",
  "Condemn",
  "Conjuration Skills",
  "Consecration",
  "Cooldown Reduction",
  "Core Skills",
  "Core Spenders Damage",
  "Corpse Explosion",
  "Corpse Skills",
  "Corpse Tendrils",
  "Counterattack",
  "Crafting Material Drop Rate",
  "Critical Strike Chance",
  "Critical Strike Damage",
  "Critical Strike Damage Multiplier",
  "Crowd Control Duration",
  "Cruel Fate: Lucky Hit Chance",
  "Cruel Fate: Vulnerable Damage",
  "Crushing Hand",
  "Curse Skills",
  "Cutthroat Skills",
  "Cyclone Armor",
  "Damage",
  "Damage Over Time Multiplier",
  "Damage Reduction",
  "Damage Reduction from Bleeding Enemies",
  "Damage Reduction from Burning Enemies",
  "Damage Reduction from Corrupted Enemies",
  "Damage Reduction from Poisoned Enemies",
  "Damage Reduction while Impaired",
  "Damage Reduction while Injured",
  "Damage for Seconds After Dodging an Attack",
  "Damage while Berserk is Active",
  "Dance of Knives",
  "Dark Pact: Damage",
  "Dark Pact: Damage Over Time",
  "Dark Pact: Lucky Hit Chance",
  "Dark Pact: Non-Physical Damage",
  "Dark Prison",
  "Dark Shroud",
  "Darkness Skills",
  "Dash",
  "Death Blow",
  "Debilitating Roar",
  "Deceptive Insight: Resource Cost Reduction",
  "Deceptive Insight: primary Resource",
  "Decompose",
  "Decrepify",
  "Defensive Skills",
  "Defiance Aura",
  "Demonology Skills",
  "Dexterity",
  "Disciple Skills",
  "Divine Lance",
  "Dodge Chance",
  "Dodge Chance Against Close Enemies",
  "Dodge Chance Against Distant Enemies",
  "Doom",
  "Double Swing",
  "Dread Claws",
  "Dust Devil",
  "Eagle Skills",
  "Earth Skills",
  "Earth Spike",
  "Earthen Bulwark",
  "Earthquake Skills",
  "Energy On Kill",
  "Energy Regeneration",
  "Essence On Kill",
  "Essence Regeneration",
  "Evade Grants Movement Speed for Seconds",
  "Faith On Kill",
  "Faith Regeneration",
  "Falling Star",
  "Familiar",
  "Fanaticism Aura",
  "Fire Bolt",
  "Fire Damage Multiplier",
  "Fire Resistance",
  "Fireball",
  "Firewall",
  "Flame Shield",
  "Flay",
  "Flesh of Abaddon: Damage Reduction while in Demonform",
  "Flesh of Abaddon: Demonform Damage Bonus",
  "Flesh of Abaddon: Fire Damage",
  "Flesh of Abaddon: Hellfire Skill Damage",
  "Flesh of Abaddon: Maximum Life",
  "Flesh of Abaddon: to Hellfire Skills",
  "Flurry",
  "Focus Skills",
  "Forceful Arrow",
  "Fortify Generation",
  "Freeze Duration",
  "Frenzy",
  "Frost Bolt",
  "Frost Nova",
  "Frost Skills",
  "Frozen Orb",
  "Fulcrum of Mefis: Attack Speed",
  "Fulcrum of Mefis: Demonology Skill Damage",
  "Fulcrum of Mefis: Lesser Demon Skill Damage",
  "Fulcrum of Mefis: Maximum Wrath",
  "Fulcrum of Mefis: chance to twist enemies into Lesser Demons",
  "Fulcrum of Mefis: to Lesser Demon Skills",
  "Fury On Kill",
  "Fury Regeneration",
  "Gold Drop Rate",
  "Golem",
  "Gorilla Skills",
  "Grenade Skills",
  "Ground Stomp",
  "Habacalva's Cauldron: Damage against Burning Enemies",
  "Habacalva's Cauldron: Fire Damage",
  "Habacalva's Cauldron: Healing Received",
  "Habacalva's Cauldron: Life On Hit",
  "Habacalva's Cauldron: Pyromancy Cooldown Reduction",
  "Habacalva's Cauldron: Pyromancy Skill Damage",
  "Hammer of the Ancients",
  "Healing Received",
  "Heartseeker",
  "Heaven's Radiant Fire: Damage to Judged Enemies",
  "Heaven's Radiant Fire: Healing Received",
  "Heaven's Radiant Fire: Holy Damage",
  "Heaven's Radiant Fire: Judicator Skill Cooldown Reduction",
  "Heaven's Radiant Fire: Judicator Skill Damage",
  "Heaven's Radiant Fire: Maximum Life",
  "Hell Fracture",
  "Hellfire Skills",
  "Hellion Sting",
  "Hemorrhage",
  "Holy Bolt",
  "Holy Damage Multiplier",
  "Holy Light Aura",
  "Human Skills",
  "Hurricane",
  "Hydra",
  "Ice Armor",
  "Ice Blades",
  "Ice Shards",
  "Imbuements Skills",
  "Impairment Reduction",
  "Incinerate",
  "Indestructible",
  "Infernal Breath",
  "Intelligence",
  "Invigorating Strike",
  "Iron Maiden",
  "Iron Shrapnel",
  "Iron Skin",
  "Jaguar Skills",
  "Judicator Skills",
  "Juggernaut Skills",
  "Justice Skills",
  "Kick",
  "Kwatli's Grace: Attacks Reduce Evade's Cooldown by seconds",
  "Kwatli's Grace: Damage Reduction while moving",
  "Kwatli's Grace: Eagle Skill Damage",
  "Kwatli's Grace: Lightning Damage",
  "Kwatli's Grace: Movement Speed",
  "Kwatli's Grace: Vulnerable Damage",
  "Landslide",
  "Leap",
  "Legacy of the Sightless: Maximum Energy",
  "Legacy of the Sightless: Maximum Life",
  "Legacy of the Sightless: Maximum Overpower Stacks",
  "Legacy of the Sightless: Ultimate Skill Cooldown Reduction",
  "Legacy of the Sightless: Ultimate Skill Damage",
  "Legacy of the Sightless: Ultimate Skills",
  "Lethality: Critical Strike Chance",
  "Lethality: Critical Strike Damage",
  "Life On Hit",
  "Life On Kill",
  "Life Regeneration",
  "Light's Epiphany: Disciple Skill Cooldown Reduction",
  "Light's Epiphany: Disciple Skill Damage",
  "Light's Epiphany: Movement Speed",
  "Light's Epiphany: Ultimate Skill Damage",
  "Light's Epiphany: Ultimate Skills",
  "Light's Epiphany: Vulnerable Damage",
  "Lightning Damage Multiplier",
  "Lightning Resistance",
  "Lightning Spear",
  "Lightning Storm",
  "Lucky Hit Chance",
  "Lucky Hit Chance while You Have a Barrier",
  "Lucky Hit: Chance to Chill for 2 Seconds",
  "Lucky Hit: Chance to Daze for 2 Seconds",
  "Lucky Hit: Chance to Deal Cold Damage",
  "Lucky Hit: Chance to Deal Fire Damage",
  "Lucky Hit: Chance to Deal Holy Damage",
  "Lucky Hit: Chance to Deal Lightning Damage",
  "Lucky Hit: Chance to Deal Physical Damage",
  "Lucky Hit: Chance to Deal Poison Damage",
  "Lucky Hit: Chance to Deal Shadow Damage",
  "Lucky Hit: Chance to Fear for 2 Seconds",
  "Lucky Hit: Chance to Freeze for 2 Seconds",
  "Lucky Hit: Chance to Immobilize for 2 Seconds",
  "Lucky Hit: Chance to Knockdown for 2 Seconds",
  "Lucky Hit: Chance to Restore Primary Resource",
  "Lucky Hit: Chance to Slow for 2 Seconds",
  "Lucky Hit: Chance to Stun for 2 Seconds",
  "Lucky Hit: Chance to Taunt for 2 Seconds",
  "Lucky Hit: Chance to for 2 Seconds",
  "Lucky Hit: Critical Strikes Have Chance to Immobilize for 2 Seconds",
  "Lucky Hit: Critical Strikes Have Chance to Slow for 2 Seconds",
  "Lucky Hit: Critical Strikes Have Chance to Stun for 2 Seconds",
  "Lunging Strike",
  "Macabre Skills",
  "Main Hand Weapon Damage",
  "Mana On Kill",
  "Mana Regeneration",
  "Marksman Skills",
  "Martial Skills",
  "Mastery Skills",
  "Mastery: Basic Skill Damage",
  "Mastery: Core Skill Damage",
  "Mastery: to All Skills",
  "Maul",
  "Maximum Energy",
  "Maximum Essence",
  "Maximum Evade Charges",
  "Maximum Fury",
  "Maximum Life",
  "Maximum Mana",
  "Maximum Resource",
  "Maximum Spirit",
  "Maximum Vigor",
  "Meteor",
  "Might of the Den Mother: Armor while in Werebear form",
  "Might of the Den Mother: Attack Speed while Berserking",
  "Might of the Den Mother: Damage while Berserking",
  "Might of the Den Mother: Damage while in Werebear form",
  "Might of the Den Mother: Werebear Skill Damage",
  "Might of the Den Mother: seconds Rampage Duration",
  "Mighty Throw",
  "Minion Skills",
  "Molten Bomb",
  "Movement Speed",
  "Nafain's Bestiary: Companion Skill Cooldown Reduction",
  "Nafain's Bestiary: Companion Skill Damage",
  "Nafain's Bestiary: Versatile Skill Damage",
  "Nafain's Bestiary: to Poison Creeper",
  "Nafain's Bestiary: to Ravens",
  "Nafain's Bestiary: to Wolves",
  "Nature Magic Skills",
  "Nether Step",
  "Nilfur's Narrow Eye: Basic Skill Damage",
  "Nilfur's Narrow Eye: Lucky Hit Chance",
  "Nilfur's Narrow Eye: Marksman Skill Cooldown Reduction",
  "Nilfur's Narrow Eye: Marksman Skill Damage",
  "Nilfur's Narrow Eye: Marksman Skills",
  "Nilfur's Narrow Eye: Movement Speed",
  "Occult Skills",
  "Overpower Damage",
  "Payback",
  "Peace of the Black Shroud: Cold Damage",
  "Peace of the Black Shroud: Damage to Crowd Controlled Enemies",
  "Peace of the Black Shroud: Darkness Skill Cooldown Reduction",
  "Peace of the Black Shroud: Darkness Skill Damage",
  "Peace of the Black Shroud: Resistance to All Elements",
  "Peace of the Black Shroud: Shadow Damage",
  "Penetrating Shot",
  "Physical Damage Multiplier",
  "Physical Resistance",
  "Poison Creeper",
  "Poison Damage Multiplier",
  "Poison Imbuement",
  "Poison Resistance",
  "Poison Trap",
  "Potency Skills",
  "Potion Capacity",
  "Potion Healing",
  "Practiced Technique: All Stats",
  "Practiced Technique: Bonus Kill Experience",
  "Practiced Technique: Dexterity",
  "Practiced Technique: Gold Drop Rate",
  "Practiced Technique: Intelligence",
  "Practiced Technique: Movement Speed",
  "Practiced Technique: Potion Capacity",
  "Practiced Technique: Strength",
  "Practiced Technique: Willpower",
  "Profane Sentinel",
  "Pulverize",
  "Puncture",
  "Purify",
  "Pyromancy Skills",
  "Quill Volley",
  "Rabies",
  "Radament's Desecration: Corpse Skill Damage",
  "Radament's Desecration: Damage against Cursed Enemies",
  "Radament's Desecration: Essence on Kill",
  "Radament's Desecration: Macabre Skill Cooldown Reduction",
  "Radament's Desecration: Macabre Skill Damage",
  "Radament's Desecration: Ultimate Skill Damage",
  "Rake",
  "Rally",
  "Rallying Cry",
  "Rampage",
  "Rampage: Lucky Hit Chance per Kill Streak Tier",
  "Rapid Fire",
  "Rathma's Walking Touch: Minion Attack Speed",
  "Rathma's Walking Touch: Minion Damage",
  "Rathma's Walking Touch: Physical Damage",
  "Rathma's Walking Touch: to Army of the Dead",
  "Rathma's Walking Touch: to Skeleton Mage",
  "Rathma's Walking Touch: to Skeleton Warrior",
  "Ravager",
  "Ravens",
  "Razor Wings",
  "Reap",
  "Reduces the number of Charms needed for Set bonuses by 1.",
  "Rend",
  "Resistance to All Elements",
  "Resource Cost Reduction",
  "Resource Generation",
  "Rezoka's Rage: Dodge Chance",
  "Rezoka's Rage: Jaguar Skill Cast Speed",
  "Rezoka's Rage: Jaguar Skill Critical Strike Chance",
  "Rezoka's Rage: Jaguar Skill Damage",
  "Rezoka's Rage: Prowess duration",
  "Rezoka's Rage: maximum Ferocity",
  "Rite of the Nameless: Occult Skill Damage",
  "Rite of the Nameless: Sigil Skill Damage",
  "Rite of the Nameless: to Occult Skills",
  "Rite of the Nameless: to Sigil of Chaos",
  "Rite of the Nameless: to Sigil of Subversion",
  "Rite of the Nameless: to Sigil of Summons",
  "Rock Splitter",
  "Rupture",
  "Rush of the Red Wolf Moon: Armor while in Werewolf form",
  "Rush of the Red Wolf Moon: Damage Over Time",
  "Rush of the Red Wolf Moon: Damage while in Werewolf form",
  "Rush of the Red Wolf Moon: Feral Rage triggers second faster",
  "Rush of the Red Wolf Moon: Movement Speed while in Werewolf form",
  "Rush of the Red Wolf Moon: Werewolf Skill Damage",
  "Rushing Claw",
  "Scourge",
  "Sescheron's Fury: Attack Speed",
  "Sescheron's Fury: Damage",
  "Sescheron's Fury: Damage Reduction",
  "Sescheron's Fury: Fury Generation",
  "Sescheron's Fury: Maximum Fury",
  "Sescheron's Fury: Maximum Life",
  "Sever",
  "Shade Skills",
  "Shadow Damage Multiplier",
  "Shadow Imbuement",
  "Shadow Resistance",
  "Shadow Step",
  "Shadow of Harash: Abyss Skill Damage",
  "Shadow of Harash: Cooldown Reduction to Abyss Skills",
  "Shadow of Harash: Damage Reduction while in Shadowform",
  "Shadow of Harash: Damage while in Shadowform",
  "Shadow of Harash: Shadow Damage",
  "Shadow of Harash: to Abyss Skills",
  "Shapeshifting Skills",
  "Shield Bash",
  "Shield Charge",
  "Shock Skills",
  "Shred",
  "Sigil of Chaos",
  "Sigil of Subversion",
  "Sigil of Summons",
  "Skeleton Mage",
  "Skeleton Warrior",
  "Slashing Skills",
  "Slaughter: Bonus Experience from Elites",
  "Slaughter: Core Skill Damage",
  "Slaughter: Damage",
  "Slaughter: Damage Reduction from Elites",
  "Slaughter: Damage to Elites",
  "Slaughter: Movement Speed for Seconds After Killing an Elite",
  "Slow Duration Reduction",
  "Smoke Grenade",
  "Soar",
  "Song of the Old Mountain: Damage to Crowd Controlled enemies",
  "Song of the Old Mountain: Damage while Fortified",
  "Song of the Old Mountain: Earth Skill Damage",
  "Song of the Old Mountain: Enemies are Petrified for seconds.",
  "Song of the Old Mountain: Nature Magic Skill Damage",
  "Song of the Old Mountain: Physical Damage",
  "Spark",
  "Spear of the Heavens",
  "Spellbound Steel: Cold Damage",
  "Spellbound Steel: Imbueable Skill Cooldown Reduction",
  "Spellbound Steel: Imbuement Skills",
  "Spellbound Steel: Poison Damage",
  "Spellbound Steel: Resistance to All Elements",
  "Spellbound Steel: Shadow Damage",
  "Spirit On Kill",
  "Spirit Regeneration",
  "Steel Grasp",
  "Stinger",
  "Stone Burst",
  "Storm Shepherd's Call: Lightning Damage",
  "Storm Shepherd's Call: Maximum Spirit",
  "Storm Shepherd's Call: Nature Magic Skill Damage",
  "Storm Shepherd's Call: Physical Damage",
  "Storm Shepherd's Call: Storm Skill Damage",
  "Storm Shepherd's Call: to Cyclone Armor",
  "Storm Skills",
  "Storm Strike",
  "Strength",
  "Subterfuge Skills",
  "Survival: All Stats",
  "Survival: Armor",
  "Survival: Maximum Life",
  "Survival: Maximum Resistance to All Elements",
  "Survivor: Healing Received.",
  "Survivor: Resistance to All Elements",
  "Tal Rasha's Threefold Way: Damage",
  "Tal Rasha's Threefold Way: Mana when a Mastery Skill is Triggered",
  "Tal Rasha's Threefold Way: Maximum Mana",
  "Tal Rasha's Threefold Way: to Ball Lightning",
  "Tal Rasha's Threefold Way: to Blizzard",
  "Tal Rasha's Threefold Way: to Meteor",
  "Teleport",
  "Thorns",
  "Thrash",
  "Thunderspike",
  "Tiraj's Uncanny Insight: Core Skill Damage",
  "Tiraj's Uncanny Insight: Defensive Cooldown Reduction",
  "Tiraj's Uncanny Insight: Enchantment Damage",
  "Tiraj's Uncanny Insight: Maximum Life",
  "Tiraj's Uncanny Insight: Resistance to All Elements",
  "Tiraj's Uncanny Insight: to Familiar",
  "Tornado",
  "Tortured Wretch",
  "Total Armor",
  "Total Armor while in Werebear Form",
  "Touch of Death",
  "Toxic Skin",
  "Trample",
  "Trap Skills",
  "Twisting Blades",
  "Tyrant's Grasp",
  "Umbral Chains",
  "Unlocks Charm Slots",
  "Upheaval",
  "Valor Skills",
  "Versatile Skills",
  "Vigor On Kill",
  "Vigor Regeneration",
  "Vortex",
  "Vulnerable Damage Multiplier",
  "Wall of Agony",
  "War Cry",
  "Way of the Blurring Blade: Agility Skill Damage",
  "Way of the Blurring Blade: Agility Skills",
  "Way of the Blurring Blade: Critical Strike Damage",
  "Way of the Blurring Blade: Cutthroat Skill Cooldown Reduction",
  "Way of the Blurring Blade: Cutthroat Skill Damage",
  "Way of the Blurring Blade: to Nearby Enemies",
  "Weapon Damage",
  "Weapon Mastery Skills",
  "Werebear Skills",
  "Werewolf Skills",
  "Whirlwind",
  "Willpower",
  "Wind Shear",
  "Withering Fist",
  "Wolves",
  "Word of the Blood Binder: Blood Skill Cooldown Reduction",
  "Word of the Blood Binder: Blood Skill Damage",
  "Word of the Blood Binder: Damage for 4 seconds after picking up a Blood Orb",
  "Word of the Blood Binder: Fortification Generation",
  "Word of the Blood Binder: Life on Kill",
  "Word of the Blood Binder: Maximum Life",
  "Wrath Regeneration",
  "Wrath Skills",
  "Wrath every 10 Kills",
  "Wumba's Embrace: Block Chance",
  "Wumba's Embrace: Blocked Damage Reduction",
  "Wumba's Embrace: Blocking has chance to pulse your Thorns",
  "Wumba's Embrace: Gorilla Skill Damage",
  "Wumba's Embrace: Thorns",
  "Wumba's Embrace: maximum Resolve",
  "Zeal",
  "Zealot Skills",
];
